### PR TITLE
Add improved Tableau color scheme, permission granted by Tableau

### PR DESCRIPTION
**Pull request by akngs**
Almost same with #16 but with the Tableau citation more explicit, which is the Tableau legal team's requirement.

### CODE REVIEW

**Comment by curran** [comment]
Interestingly, it appears `category10` is the original Tableau color scheme.

image

From [How we designed the new color palettes in Tableau 10](https://www.tableau.com/about/blog/2016/7/colors-upgrade-tableau-10-56782#2K30L3j1pKm0YqDd.99)

**Comment by akngs** [comment]
> Interestingly, it appears `category10` is the original Tableau color scheme.

Yes, indeed. Tableau's original color scheme is used virtually everywhere. Various packages of R and Python also use the same color set, but I don't see a clear reason why it is so popular.

**Comment by mbostock** [comment]
For D3, the provenance starts with Prefuse Flare:

https://github.com/prefuse/Flare/blob/1166bcf5516bf2ee12be0ca37fe206ae07b825d2/flare/src/flare/util/palette/ColorPalette.as#L57-L61

Which was ported to Protovis:

https://github.com/mbostock/protovis/blob/fe258ac630b2107b6acc1156cab91a6ba29d2090/src/color/Colors.js#L50-L56

Which was ported to D3:

https://github.com/d3/d3/blob/8da80dcc994ef660198b5cf2b88343c429296847/src/scale/category.js#L22-L25

And which now lives in d3-scale-chromatic:

https://github.com/d3/d3-scale-chromatic/blob/f8d13955d2c20b2f1ee7a20fe795096ad55a012a/src/categorical/category10.js#L3

**Comment by mbostock** [comment]
Tableau is the original—Jeff Heer (the author of Prefuse and Prefuse Flare) was an intern at Tableau.

**Comment by curran** [comment]
Any thoughts regarding mergeability of this PR?

**Comment by mbostock** [comment]
Thanks for the PR! And apologies for the delay. 😄

**Pull request merged**
